### ISSUE TITLE
侧滑返回，视频播放卡顿

### ISSUE THREAD

**Issue by EverMe** [JarvisHot/JWAVPlayer#1]
结构为Nav->vc1->vc2 当player在vc2中，侧滑返回至vc1时，player会播放卡顿。请问作者知道原因么？

**Comment by shitaBro** [comment]
plaler在vc1中还在播放吗？，你可以在viewdisappear时暂停

**Comment by shitaBro** [comment]
[CADisplayLink displayLinkWithTarget:self selector:@selector(upadte)];//和屏幕频率刷新

你把player里面这个关掉

**Comment by EverMe** [comment]
player在vc2中正在播放， 当手势返回vc1，如果想让player正常播放的话，应该注意什么？  这个是描述bug的小demo ：https://github.com/EverMe/SwipeBackBug

**Comment by shitaBro** [comment]
😅，你写个播放器单例类去管理！pop的时候不停止就行了

**Comment by EverMe** [comment]
本来就没想它停止，是pop的时候播放变得卡顿的问题！！！

**Comment by shitaBro** [comment]
你写的代码，pop后vc2就释放了啊，player也释放了

发自网易邮箱大师
在2016年11月19日 02:03，Somnus 写道:

本来就没想它停止，是pop的播放卡顿 查了很多资料没有原因

**Comment by EverMe** [comment]
可能是我表述的有问题，不好意思。 就是手势返回的过程中，就是vc2慢慢的手势返回到vc1但始终没放手没有完全的pop回去，手势来回左右滑动，在这个过程中，player会变的卡顿。但是我看bilibili和今日头条等app ，在此过程都没有出现这个问题，项目中又用到这一块，所以想查明原因。但下了很多封装avplayer的demo 发现都有此问题（当然也试了您写的JWAVPlayer）。如果看了链接中这个表述bug的demo，会发现，这个过程中，不仅player卡顿，而且SDWebImage加载的Gif也是有问题的。

**Comment by desperadocarl** [comment]
对 avplayer有这个bug  你解决了吗

**Comment by shitaBro** [comment]
你看看ZFplayer吧，那个什么情况都考虑了

**Comment by desperadocarl** [comment]
嗯 其实也没有都考虑 但这个bug他解决了 自己写了一个滑动返回手势 我注意到了 2个没有这个bug的播放器 都是这么处理的
