### ISSUE TITLE
添加到的viewcontroller ,  viewcontroller POP出去后， 没有调用dealloc

### ISSUE THREAD

**Issue by AngryOC** [JarvisHot/JWAVPlayer#2]
JWPlayer*player=[[JWPlayer alloc]initWithFrame:CGRectMake(0, 0, SCREEN_WIDTH,kVideoH)];
            [player updatePlayerWith:[NSURL URLWithString:self.productInfo.videoPath]];
            [player showInSuperView:scrollView andSuperVC:self];
            self.player = player;

你好， 感谢你的分享， 我项目中用了你的代码块， push到新的vc的然后 在vc上添加一个scrollview， 再在scrollview上添加player,  当这个vc pop 出去后， 应该调用dealloc:的， 结果没有， 我的视屏资源销毁实在dealloc中添加的； 不自动调用 会产生 多视频流 同时播放； 排除法确定 是这段代码的问题， 导致 VC不能释放， 我没做改进，只是换种放是销毁视频资源了.....

**Comment by shitaBro** [comment]
你好，谢谢你的反馈，确实有这个问题，我研究一下，尽快更改

**Comment by shitaBro** [comment]
在viewWillDisappear 调用`[self.player removeObserverAndNotification]; `这个方法就好了

**Comment by AngryOC** [comment]
嗯嗯 ，  这样是可以的，解决了多视频流播放的问题， 但还是没有自动调用 dealloc, 说明vc还是没有释放， 多创建这样的页面会使内存消耗较多的， 我这边暂时这样了， 能满足需求了， 谢谢哈。

- (void) viewDidDisappear:(BOOL)animated {
    [super viewDidDisappear:YES];
    NSLog(@"count  %lu", self.navigationController.viewControllers.count);

    if (self.navigationController.viewControllers.count == 0) { //判断是pop出去了
        if(self.player.isPlaying){
            [self.player pause];
        }
        [self.player removeObserverAndNotification];
    }
}

**Comment by shitaBro** [comment]
我最近看到一个库ZFplayer写的还不错，你可以看一下，功能比较全
